### ISSUE TITLE
Potential collision and risk from indirect dependence "github.com/godbus/dbus"

### ISSUE THREAD

**Issue by KateGo520** [andy-zhangtao/ntci#12]
## Dependency line:

github.com/andy-zhangtao/ntci --> [github.com/coreos/go-systemd](https://github.com/andy-zhangtao/ntci/blob/master/go.mod#L7) --> [github.com/godbus/dbus](https://github.com/andy-zhangtao/ntci/blob/master/go.mod#L8) -

github.com/coreos/go-systemd fd7a80b  -->  github.com/godbus/dbus 4481cbc (close to v5.0.2)
https://github.com/coreos/go-systemd/blob/fd7a80b32e1fc73e890fde45604ed5009dc817a3/Gopkg.toml#L7 
```
[[constraint]]
  name = "github.com/godbus/dbus"
  version = "5.0"
```

## Background
The `godbus/dbus` has already opted into module since the version updated to `v5`. Repo `github.com/coreos/go-systemd` didn’t have module in the commit fd7a80b, so use the import path "github.com/godbus/dbus" to get `godbus/dbus`.
This repo `github.com/andy-zhangtao/ntci` has already opted into module. So when `github.com/andy-zhangtao/ntci` try to get `godbus/dbus` through the indirect path "github.com/godbus/dbus", module pulled the last version of `godbus/dbus` which didn’t have go.mod, `v4.1.0`. From the Go Modules's point of view, path `"github.com/godbus/dbus"` equals to `version v0/v1 or the latest version that didn’t use the module`.

This resulted in version of `godbus/dbus` sticking at v4.1.0:
https://github.com/andy-zhangtao/ntci/blob/master/go.mod#L8
```
github.com/godbus/dbus v4.1.0+incompatible // indirect
```
And actually the version that `github.com/coreos/go-systemd` required is v5. This inconsistency may bring potential errors and problems

## Solution
Add replace statement in the go.mod file:
```
replace github.com/godbus/dbus => github.com/godbus/dbus 66d97ae
```

**Comment by KateGo520** [comment]
@andy-zhangtao  Could you help me review this issue? Thx :p

**Comment by andy-zhangtao** [comment]
Sure. Tks for this issue.
